# 大模型配置

# OpenAI 兼容接口
api_url: "https://yinli.one/v1/chat/completions"
api_key: "${OPENAI_API_KEY}"
model: "gpt-4o"
temperature: 0.3
max_tokens: 4096


LANGCHAIN_TRACING_V2: "true"
LANGCHAIN_API_KEY: "${LANGCHAIN_API_KEY}"

TAVILY_API_KEY: "${TAVILY_API_KEY}"
gaode_demo_key: "${GAODE_DEMO_KEY}"

LANGSMITH_TRACING: true
LANGSMITH_API_KEY: "${LANGSMITH_API_KEY}"
LANGSMITH_PROJECT: langgraph_studio_chatbot